-- Run once in Supabase SQL Editor
begin;
create table if not exists public.service_images (
  id bigint generated by default as identity primary key,
  service_key text not null,
  image_url text not null,
  media_type text not null default 'image' check (media_type in ('image','video')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.service_images add column if not exists media_type text not null default 'image';
create index if not exists service_images_key_order_idx on public.service_images(service_key,sort_order);
alter table public.service_images enable row level security;
commit;
