create table if not exists public.service_images (
 id bigint generated by default as identity primary key,
 service_key text not null, image_url text not null, sort_order integer not null default 0, created_at timestamptz not null default now()
);
create index if not exists service_images_key_order_idx on public.service_images(service_key,sort_order);
alter table public.service_images enable row level security;
-- The server uses the service-role key; no public write policy is required.
